name: meal_planner
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  table_calendar: ^3.0.9
  core:
    path: ../core
  data:
    path: ../data
  shared_ui:
    path: ../shared_ui
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
