name: capture
resolution: workspace
description: Services for scanning receipts and barcodes.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.12.0
  mobile_scanner: ^3.5.7
  image_picker: ^1.1.2
  http: ^1.2.1
  path: ^1.9.0
  intl: ^0.20.0
  image: ^4.1.7
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
