name: parsing
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  core:
    path: ../core
  collection: ^1.18.0
  html: ^0.15.4
  http: ^1.2.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
